services:
  # ===================== KEYCLOAK DB (POSTGRES) =====================
  postgres-keycloak:
    image: postgres:16.2
    container_name: postgres-keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - tpi-network

  # ===================== KEYCLOAK =====================
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    restart: always
    depends_on:
      - postgres-keycloak
    networks:
      - tpi-network

  # ===================== COMPRAS BACKEND =====================
  backend-compras:
    container_name: backend-compras
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - STOCK_API_URL=http://stock:8000/v1
      - LOGISTICS_API_URL=http://shipping_back:3010
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/ds-2025-realm
      - SHIPPING_API_URL=${SHIPPING_API_URL}
      - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - SHIPPING_SCOPES=${SHIPPING_SCOPES}
    volumes:
      - ./backend:/app
    networks:
      - tpi-network
    depends_on:
      - keycloak
      - stock
      - shipping_back

  # ===================== COMPRAS FRONTEND =====================
  frontend-compras:
    container_name: frontend-compras
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
    - NEXT_PUBLIC_API_URL=http://localhost:8001/v1
    networks:
      - tpi-network
    depends_on:
      - backend-compras
      
  # ===================== STOCK =====================
  stock:
    container_name: stock-service
    image: fariasvalentino25/docker-stock_backend_api:latest
    ports:
      - "8001:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: aws-1-us-east-2.pooler.supabase.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres.vzabfnzrcynffhdjdddv
      DB_PASSWORD: TNNczJndvipl7Kgk
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/ds-2025-realm/protocol/openid-connect/token
      KEYCLOAK_CLIENT_ID: grupo-13
      KEYCLOAK_CLIENT_SECRET: 404249de-18ba-403c-b45c-d82c446e2a2a
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/ds-2025-realm
      KEYCLOAK_AUDIENCE: grupo-13
    networks:
      - tpi-network
    depends_on:
      - keycloak

  # ===================== LOGISTICA =====================
  shipping_mysql:
    image: mysql:8.0
    container_name: shipping_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: shipping_db
      MYSQL_USER: shipping_user
      MYSQL_PASSWORD: shipping_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "shipping_user", "-pshipping_pass"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - tpi-network

  shipping_back:
    image: ghcr.io/frre-ds/2025-grupo-03-backend-logistica:e620c72c0d53f8c41a551bcbbf5b12fb3aee6e49
    container_name: shipping_back
    restart: always
    environment:
      DB_HOST: shipping_mysql
      DB_PORT: 3306
      DB_USERNAME: shipping_user
      DB_PASSWORD: shipping_pass
      DB_DATABASE: shipping_db
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/ds-2025-realm/protocol/openid-connect/token
      KEYCLOAK_CLIENT_ID: grupo-13
      KEYCLOAK_CLIENT_SECRET: 404249de-18ba-403c-b45c-d82c446e2a2a
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/ds-2025-realm
      KEYCLOAK_AUDIENCE: grupo-13
    depends_on:
      shipping_mysql:
        condition: service_healthy
    ports:
      - "3010:3010"
    networks:
      - tpi-network

volumes:
  mysql_data:
  postgres_data:

networks:
  tpi-network:
    external: true
